services:
  bot:
    container_name: ${DOCKER_PREFIX}bot
    image: oven/bun:1.0.31
    restart: always
    volumes:
      - .:/home/bun/app
    command: bun --watch run index.ts
    tty: true
    depends_on:
      - lavalink

  lavalink:
    container_name: ${DOCKER_PREFIX}lavalink
    image: ghcr.io/lavalink-devs/lavalink:4.0.4
    restart: always
    expose:
      - ${LAVALINK_PORT}
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=${LAVALINK_PORT}
      - LAVALINK_SERVER_PASSWORD=${LAVALINK_PASSWORD}

networks:
  default:
