services:
  bot:
    container_name: bot
    image: oven/bun:1.2.22
    restart: always
    volumes:
      - .:/home/bun/app
    entrypoint: bun run --install=auto main.ts
    depends_on:
      - lavalink

  lavalink:
    container_name: lavalink
    image: ghcr.io/lavalink-devs/lavalink:4.0.6
    restart: always
    volumes:
      - ./lavalink/application.yml:/opt/Lavalink/application.yml
    ports:
      - "2333:2333"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=2333

networks:
  default:
