services:
  bot:
    container_name: ${DOCKER_PREFIX}bot
    image: oven/bun:1.1.17
    restart: always
    volumes:
      - .:/home/bun/app
    command: /bin/sh -c 'bun install && bun run index.ts'
    tty: true
    depends_on:
      - lavalink

  lavalink:
    container_name: ${DOCKER_PREFIX}lavalink
    image: ghcr.io/lavalink-devs/lavalink:v4-update-lp
    restart: always
    expose:
      - ${LAVALINK_PORT}
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=${LAVALINK_PORT}
      - LAVALINK_SERVER_PASSWORD=${LAVALINK_PASSWORD}
      - SENTRY_DSN=${SENTRY_DSN}

networks:
  default:
